[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "DiamondStats"
version = "0.1.0"
description = "A sample Python module"
authors = [{name = "Your Name", email = "your.email@example.com"}]
dependencies = [
    # 必要な依存関係を記述
]